### ISSUE TITLE
current temperature problem

### ISSUE THREAD

**Issue by orich4322** [eibenp/homebridge-gree-airconditioner#20]
**Describe The Bug:**

I have a Tadiran AC that works perfectly with gree but I’m using homekit (with homebridge of course).
There are several problems with it:
1. It says the current temperature is -40 degrees (on the accessory).
2. When I create an automation and set the AC to turn on and set to 24 degrees, it does it with 22 degrees.
3. I want that the apple homekit will be able to control the light (that shows the temperature) on the AC.
4. In heat mod, I cant go higher than 25 degrees (I want 30)

**To Reproduce:**

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

![IMG_5712](https://github.com/user-attachments/assets/c287dbb1-1d95-4b43-bfee-ba9296bcf1bd)
![IMG_5713](https://github.com/user-attachments/assets/22973be7-320d-469e-9feb-1b28fcc10635)
![IMG_5714](https://github.com/user-attachments/assets/914e6370-9937-4aad-b82a-a90422a32af5)

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: 
* Raspbian

**Comment by eibenp** [comment]
Please attach plugin config and debug logs to analyze your issues!
It seems that you have set sensorOffset to 0 instead of the default 40 but I am not sure until I see your configuration settings.

**Comment by eibenp** [comment]
Hi @orich4322 

I am still waiting for plugin config and debug log...
I have analyzed your issue and I can answer some questions:

> 1. It says the current temperature is -40 degrees (on the accessory).

I have found a bug in processing data received from temperature sensor. I have fixed it in version 2.1.5. Please upgrade to the latest version before you create debug logs. I do not think any more that you have set sensorOffset to 0. -40 is a bug which is solved in the latest version. Unfortunately there are some firmware versions which do not report data from the built-in temperature sensor. In this case the plugin can't access the room temperature and the target temperature is used. Only a firmware upgrade or downgrade can solve this problem. This is documented in plugin's readme.

> 2. When I create an automation and set the AC to turn on and set to 24 degrees, it does it with 22 degrees.

Automations do not depend on this plugin nor on homebridge. As I know automations save the target temperature value upon definition. If the AC unit was set to 22 degrees at the time the automation was saved then Home App will turn it on to 22 degrees. Please ask Apple's support for more information.

> 3. I want that the apple homekit will be able to control the light (that shows the temperature) on the AC.

This plugin was designed to support the Home App's HeaterCooler accessory. Apple's HeaterCooler does not support the light. It is not on my short time plan to add this feature to the plugin because it is not supported by Apple and could make the UI confusing.

> 4. In heat mod, I cant go higher than 25 degrees (I want 30)

This is not a bug, this is documented in plugin's readme. (Please read the known limitations section!) When adding the accessory to Home App it is not possible to set the minimum and maximum values. They can be set only in active cooling and heating modes. So initially the maximum value is 25 degrees which is Apple's default value. On first time use the plugin updates the minimum and maximum values but you can see the new limits only after restarting the Home App. Next time you open the Home App the correct minimum and maximum values are accessible and you can set heating to 30 degrees.

**Comment by orich4322** [comment]
Hello
Thank you a lot for your help
About 4, I’ve set the maximum temperature to be 30 when I added the device in the first place.
I’ve restarted the apple home app several times and it still doesn’t let me set the temperature above 25 in heating mode.
I’m using the heat mode.
Thank for you help!!

**Comment by eibenp** [comment]
Hi @orich4322 ,

I have added some comments about Home App restart to the plugin readme yesterday. Home App restart means that the Home App must be removed from device memory before starting again. On iPhone the following steps are required:

1. From the Home Screen, swipe up from the bottom of the screen and pause in the middle of the screen.
2. Swipe right or left to find the app that you want to close.
3. Swipe up on the app's preview to close the app.

On iPad follow these steps:

1. Swipe up from the bottom of the screen and hold. You will see all open apps and their preview.
2. Swipe horizontally to find the app you wish to close. Finally, swipe up on an app card to force quit it.

Did you do the above steps? If yes please try to restart your iPhone or iPad and check the acceptable maximum temperature again. Please tell me the result!

Thank You!

**Comment by orich4322** [comment]
Yes of course I closed the home app (removed from memory) but it still cant go higher than 25 on heat.
What can i do?

**Comment by eibenp** [comment]
I am working on a solution. Please be patient while it's done.
